services:
  client:
    build:
      context: client
      args:
        BACKEND_URL: ${BACKEND_URL}
    container_name: belief-client
    ports:
      - 5173:5173
    networks:
      - app-network
    depends_on:
      - server

  server:
    build: server
    container_name: belief-server
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy


  mongodb:
    image: mongo:8.0
    container_name: belief-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongodb_data:

networks:
  app-network: